project:
  name: lab1_cloudformation_group15
  regions:
    - us-east-1
    - us-west-2
  template: main.yaml

tests:
  group15-test:
    template: main.yaml
    regions:
      - us-east-1
    tags:
      Project: lab1_cloudformation_group15