project:
  name: group15-test
  
  regions:
    - us-east-1
  template: main.yml

tests:
  group15-test:
    template: main.yml
    parameters: 
      UniqueName: test
      KeyName: demo1
      AllowedSSHIP: 14.187.92.162/32
    regions:
      - us-east-1
    tags:
      Project: lab1_cloudformation_group15